version: '3.7'
services:
  sample:
    container_name: driver-locations
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080